// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: worker.v1.proto

package api

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *RunRequest) Validate() error {
	if len(this.Endpoints) < 1 {
		return github_com_mwitkow_go_proto_validators.FieldError("Endpoints", fmt.Errorf(`value '%v' must contain at least 1 elements`, this.Endpoints))
	}
	if len(this.Endpoints) > 1000 {
		return github_com_mwitkow_go_proto_validators.FieldError("Endpoints", fmt.Errorf(`value '%v' must contain at most 1000 elements`, this.Endpoints))
	}
	for _, item := range this.Endpoints {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Endpoints", err)
			}
		}
	}
	if !(this.Amount > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Amount", fmt.Errorf(`value '%v' must be greater than '0'`, this.Amount))
	}
	if !(this.Amount < 500) {
		return github_com_mwitkow_go_proto_validators.FieldError("Amount", fmt.Errorf(`value '%v' must be less than '500'`, this.Amount))
	}
	if _, ok := RunRequest_BrowserType_name[int32(this.Type)]; !ok {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a valid RunRequest_BrowserType field`, this.Type))
	}
	if !(this.MinWaitTime > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("MinWaitTime", fmt.Errorf(`value '%v' must be greater than '0'`, this.MinWaitTime))
	}
	if !(this.MinWaitTime < 3600000) {
		return github_com_mwitkow_go_proto_validators.FieldError("MinWaitTime", fmt.Errorf(`value '%v' must be less than '3600000'`, this.MinWaitTime))
	}
	if !(this.MaxWaitTime > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("MaxWaitTime", fmt.Errorf(`value '%v' must be greater than '0'`, this.MaxWaitTime))
	}
	if !(this.MaxWaitTime < 3600000) {
		return github_com_mwitkow_go_proto_validators.FieldError("MaxWaitTime", fmt.Errorf(`value '%v' must be less than '3600000'`, this.MaxWaitTime))
	}
	return nil
}

var _regex_RunRequest_Endpoint_Url = regexp.MustCompile(`^(http|https)://(.*)`)

func (this *RunRequest_Endpoint) Validate() error {
	if !_regex_RunRequest_Endpoint_Url.MatchString(this.Url) {
		return github_com_mwitkow_go_proto_validators.FieldError("Url", fmt.Errorf(`value '%v' must be a string conforming to regex "^(http|https)://(.*)"`, this.Url))
	}
	if !(this.Weight > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Weight", fmt.Errorf(`value '%v' must be greater than '0'`, this.Weight))
	}
	if !(this.Weight < 1000) {
		return github_com_mwitkow_go_proto_validators.FieldError("Weight", fmt.Errorf(`value '%v' must be less than '1000'`, this.Weight))
	}
	return nil
}
func (this *EndpointResult) Validate() error {
	return nil
}
func (this *PingRequest) Validate() error {
	return nil
}
func (this *PingResponse) Validate() error {
	return nil
}
