// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker.v1.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunRequest_BrowserType int32

const (
	RunRequest_FAKE   RunRequest_BrowserType = 0
	RunRequest_CHROME RunRequest_BrowserType = 1
)

var RunRequest_BrowserType_name = map[int32]string{
	0: "FAKE",
	1: "CHROME",
}

var RunRequest_BrowserType_value = map[string]int32{
	"FAKE":   0,
	"CHROME": 1,
}

func (x RunRequest_BrowserType) String() string {
	return proto.EnumName(RunRequest_BrowserType_name, int32(x))
}

func (RunRequest_BrowserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2c191f458cd55dd, []int{0, 0}
}

type RunRequest struct {
	Endpoints            []*RunRequest_Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Amount               uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 RunRequest_BrowserType `protobuf:"varint,3,opt,name=type,proto3,enum=v1.RunRequest_BrowserType" json:"type,omitempty"`
	MinWaitTime          uint32                 `protobuf:"varint,4,opt,name=minWaitTime,proto3" json:"minWaitTime,omitempty"`
	MaxWaitTime          uint32                 `protobuf:"varint,5,opt,name=maxWaitTime,proto3" json:"maxWaitTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c191f458cd55dd, []int{0}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetEndpoints() []*RunRequest_Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *RunRequest) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RunRequest) GetType() RunRequest_BrowserType {
	if m != nil {
		return m.Type
	}
	return RunRequest_FAKE
}

func (m *RunRequest) GetMinWaitTime() uint32 {
	if m != nil {
		return m.MinWaitTime
	}
	return 0
}

func (m *RunRequest) GetMaxWaitTime() uint32 {
	if m != nil {
		return m.MaxWaitTime
	}
	return 0
}

type RunRequest_Endpoint struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Weight               uint32   `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunRequest_Endpoint) Reset()         { *m = RunRequest_Endpoint{} }
func (m *RunRequest_Endpoint) String() string { return proto.CompactTextString(m) }
func (*RunRequest_Endpoint) ProtoMessage()    {}
func (*RunRequest_Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c191f458cd55dd, []int{0, 0}
}

func (m *RunRequest_Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest_Endpoint.Unmarshal(m, b)
}
func (m *RunRequest_Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest_Endpoint.Marshal(b, m, deterministic)
}
func (m *RunRequest_Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest_Endpoint.Merge(m, src)
}
func (m *RunRequest_Endpoint) XXX_Size() int {
	return xxx_messageInfo_RunRequest_Endpoint.Size(m)
}
func (m *RunRequest_Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest_Endpoint proto.InternalMessageInfo

func (m *RunRequest_Endpoint) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RunRequest_Endpoint) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type EndpointResult struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	HttpStatusCode       int32    `protobuf:"varint,2,opt,name=httpStatusCode,proto3" json:"httpStatusCode,omitempty"`
	HttpStatusMessage    string   `protobuf:"bytes,3,opt,name=httpStatusMessage,proto3" json:"httpStatusMessage,omitempty"`
	Ttfb                 int32    `protobuf:"varint,4,opt,name=ttfb,proto3" json:"ttfb,omitempty"`
	Cached               bool     `protobuf:"varint,5,opt,name=cached,proto3" json:"cached,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointResult) Reset()         { *m = EndpointResult{} }
func (m *EndpointResult) String() string { return proto.CompactTextString(m) }
func (*EndpointResult) ProtoMessage()    {}
func (*EndpointResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2c191f458cd55dd, []int{1}
}

func (m *EndpointResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointResult.Unmarshal(m, b)
}
func (m *EndpointResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointResult.Marshal(b, m, deterministic)
}
func (m *EndpointResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointResult.Merge(m, src)
}
func (m *EndpointResult) XXX_Size() int {
	return xxx_messageInfo_EndpointResult.Size(m)
}
func (m *EndpointResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointResult.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointResult proto.InternalMessageInfo

func (m *EndpointResult) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EndpointResult) GetHttpStatusCode() int32 {
	if m != nil {
		return m.HttpStatusCode
	}
	return 0
}

func (m *EndpointResult) GetHttpStatusMessage() string {
	if m != nil {
		return m.HttpStatusMessage
	}
	return ""
}

func (m *EndpointResult) GetTtfb() int32 {
	if m != nil {
		return m.Ttfb
	}
	return 0
}

func (m *EndpointResult) GetCached() bool {
	if m != nil {
		return m.Cached
	}
	return false
}

func init() {
	proto.RegisterEnum("v1.RunRequest_BrowserType", RunRequest_BrowserType_name, RunRequest_BrowserType_value)
	proto.RegisterType((*RunRequest)(nil), "v1.RunRequest")
	proto.RegisterType((*RunRequest_Endpoint)(nil), "v1.RunRequest.Endpoint")
	proto.RegisterType((*EndpointResult)(nil), "v1.EndpointResult")
}

func init() { proto.RegisterFile("worker.v1.proto", fileDescriptor_c2c191f458cd55dd) }

var fileDescriptor_c2c191f458cd55dd = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xee, 0x5e, 0xda, 0xa4, 0x9d, 0x62, 0x8d, 0x8b, 0x9c, 0x21, 0x2f, 0xad, 0x15, 0x24, 0x27,
	0xd7, 0xc4, 0xab, 0xe0, 0x81, 0xbe, 0x68, 0x8e, 0x8a, 0x20, 0x87, 0xb0, 0x1e, 0x1c, 0x28, 0x88,
	0xdb, 0x76, 0x6d, 0x96, 0x6b, 0xb2, 0x31, 0xbb, 0x69, 0x3c, 0xf0, 0xc1, 0x47, 0xf1, 0x77, 0xf8,
	0xaf, 0x44, 0x0a, 0x7d, 0xba, 0x1f, 0xe0, 0x0f, 0x90, 0x6c, 0x7b, 0xd7, 0x5e, 0xbd, 0x97, 0x30,
	0x33, 0xdf, 0x37, 0xf9, 0xe6, 0x9b, 0x1d, 0xb8, 0x5d, 0x88, 0xec, 0x8c, 0x65, 0xfe, 0xec, 0xc0,
	0x4f, 0x33, 0xa1, 0x04, 0xde, 0x99, 0x1d, 0xb8, 0x4f, 0x27, 0x5c, 0x45, 0xf9, 0xd0, 0x1f, 0x89,
	0x38, 0x88, 0x0b, 0xae, 0xce, 0x44, 0x11, 0x4c, 0x44, 0x4f, 0x13, 0x7a, 0x33, 0x3a, 0xe5, 0x63,
	0xaa, 0x44, 0x26, 0x83, 0xab, 0x70, 0xd9, 0xdb, 0xfd, 0x69, 0x00, 0x90, 0x3c, 0x21, 0xec, 0x4b,
	0xce, 0xa4, 0xc2, 0x2f, 0xa0, 0xc1, 0x92, 0x71, 0x2a, 0x78, 0xa2, 0xa4, 0x83, 0x3a, 0x86, 0xd7,
	0xec, 0xdf, 0x2b, 0x85, 0xd6, 0x14, 0x7f, 0xb0, 0xc2, 0xc3, 0xc6, 0x62, 0xde, 0xae, 0x7d, 0x42,
	0xd1, 0x85, 0x45, 0xd6, 0x4d, 0xf8, 0x3e, 0x98, 0x34, 0x16, 0x79, 0xa2, 0x9c, 0x9d, 0x0e, 0xf2,
	0x6e, 0x2d, 0x59, 0x76, 0xc5, 0xf9, 0x6b, 0x90, 0x15, 0x80, 0x0f, 0xa1, 0xaa, 0xce, 0x53, 0xe6,
	0x18, 0x1d, 0xe4, 0xb5, 0xfa, 0xee, 0xd6, 0xff, 0xc3, 0x4c, 0x14, 0x92, 0x65, 0x27, 0xe7, 0x29,
	0x0b, 0xad, 0xc5, 0xbc, 0x6d, 0xfc, 0x40, 0x88, 0xe8, 0x06, 0xdc, 0x83, 0x66, 0xcc, 0x93, 0x53,
	0xca, 0xd5, 0x09, 0x8f, 0x99, 0x53, 0xd5, 0x02, 0xcd, 0xc5, 0xbc, 0x6d, 0xd9, 0x15, 0xe7, 0xfb,
	0x9f, 0xdf, 0x88, 0x6c, 0xe2, 0x9a, 0x4e, 0xbf, 0x5e, 0xd1, 0x6b, 0x37, 0xd1, 0xd7, 0xb8, 0xfb,
	0x01, 0xea, 0x97, 0xde, 0xf0, 0x3e, 0x18, 0x79, 0x36, 0x75, 0x50, 0x07, 0x79, 0x8d, 0xd0, 0x5d,
	0xcc, 0xdb, 0xbb, 0x70, 0xf7, 0xa3, 0x17, 0x29, 0x95, 0x7e, 0x2b, 0x3f, 0x72, 0xef, 0x59, 0x10,
	0x78, 0xfe, 0xa3, 0x3d, 0x52, 0xd2, 0x4a, 0xcf, 0x05, 0xe3, 0x93, 0x68, 0xdb, 0xf3, 0x85, 0x45,
	0x56, 0x40, 0xf7, 0x01, 0x34, 0x37, 0x8c, 0xe1, 0x3a, 0x54, 0x5f, 0xbd, 0x7c, 0x33, 0xb0, 0x2b,
	0x18, 0xc0, 0x3c, 0x7a, 0x4d, 0xde, 0x1e, 0x0f, 0x6c, 0xd4, 0xfd, 0x85, 0xa0, 0x75, 0x39, 0x02,
	0x61, 0x32, 0x9f, 0x2a, 0x6c, 0x6f, 0x0c, 0xb2, 0x14, 0x7b, 0x08, 0xad, 0x72, 0x84, 0x77, 0x8a,
	0xaa, 0x5c, 0x1e, 0x89, 0x31, 0xd3, 0xa2, 0x35, 0xb2, 0x55, 0xc5, 0xfb, 0x70, 0x67, 0x5d, 0x39,
	0x66, 0x52, 0xd2, 0xc9, 0x72, 0xe5, 0x0d, 0xf2, 0x3f, 0x80, 0x31, 0x54, 0x95, 0xfa, 0x3c, 0xd4,
	0x3b, 0xad, 0x11, 0x1d, 0xe3, 0x5d, 0x30, 0x47, 0x74, 0x14, 0xb1, 0xb1, 0x5e, 0x5d, 0x9d, 0xac,
	0xb2, 0xfe, 0x21, 0x98, 0xa7, 0xfa, 0x04, 0x71, 0x0f, 0x0c, 0x92, 0x27, 0xb8, 0x75, 0xfd, 0x09,
	0x5d, 0x5c, 0xe6, 0xd7, 0x8d, 0x74, 0x2b, 0x8f, 0x51, 0x68, 0xbd, 0xaf, 0xf9, 0xcf, 0x69, 0xca,
	0x87, 0xa6, 0x3e, 0xbe, 0x27, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xcb, 0x84, 0xf0, 0xcb,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (Worker_RunClient, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (Worker_RunClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Worker_serviceDesc.Streams[0], "/v1.Worker/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerRunClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Worker_RunClient interface {
	Recv() (*EndpointResult, error)
	grpc.ClientStream
}

type workerRunClient struct {
	grpc.ClientStream
}

func (x *workerRunClient) Recv() (*EndpointResult, error) {
	m := new(EndpointResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	Run(*RunRequest, Worker_RunServer) error
}

// UnimplementedWorkerServer can be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (*UnimplementedWorkerServer) Run(req *RunRequest, srv Worker_RunServer) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).Run(m, &workerRunServer{stream})
}

type Worker_RunServer interface {
	Send(*EndpointResult) error
	grpc.ServerStream
}

type workerRunServer struct {
	grpc.ServerStream
}

func (x *workerRunServer) Send(m *EndpointResult) error {
	return x.ServerStream.SendMsg(m)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _Worker_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "worker.v1.proto",
}
