name: GoDoc
on:
  push:
    tags:
      - '*'

env:
  GOPROXY: https://proxy.golang.org

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Refresh proxy
        run : test $(curl -s -o /dev/null -w "%{http_code}" ${GOPROXY}/github.com/mittwald/goharbor-client/@v/${GITHUB_REF/refs\/tags\//}.info) -eq 200
